### ISSUE TITLE
Need /dev/i2c-1 available on the Radxa Zero

### ISSUE THREAD

**Issue by wjlove** [balena-os/balena-radxa#172]
According to the Radxa Zero Wiki, there are 3 i2c busses available on the 40-pin header: 

 I2C (x3); I2C_EE_M1 (/dev/i2c-1), I2C_EE_M3 (/dev/i2c-3), I2C_AO_M0 (/dev/i2c-4)  

Currently none of these appear to be available upon boot.    Having i2c-1 available would be helpful to the balenAIR project.

**Comment by wjlove** [comment]
As an experiment I installed the Radxa Zero version of Ubuntu and it does make the /dev/i2c-1 device available.  I also found a note here: https://wiki.radxa.com/Device-tree-overlays for the Meson (Amlogic S905Y2) that appear to talk about what extra overlays are need for the i2c and spi devices.  Not sure if that helps but I though I'd share it anyway.

**Comment by wjlove** [comment]
Update:  Digging into this further, it appears that for this board having /dev/i2c-3 available would be better as it physically maps to the raspi pinout.  Also, further research leads me to think that adding this overlay: `meson-g12a-i2c-ee-m3-gpioa-14-gpioa-15` would accomplish this.

**Comment by floion** [comment]
@wjlove https://github.com/balena-os/balena-radxa/pull/183 should fix it
Once this gets deployed, you should use the webterminal and edit `/mnt/boot/uEnv.txt` and add your overlay to it. For example:

```
overlays=meson-g12a-uart-ao-a-on-gpioao-0-gpioao-1 meson-g12a-i2c-ee-m3-gpioa-14-gpioa-15
```

**Comment by wjlove** [comment]
Manually adding the entry `meson-g12a-i2c-ee-m3-gpioa-14-gpioa-15` to the uEnv.txt file before booting produced the hoped for results.  The I2C entry `/dev/i2c-3` was created and I2C devices on that bus can be seen with i2cdetect.

**Comment by floion** [comment]
@wjlove OS version `2.102.1` is available in staging. Can you test it out and close this issue if all good?

**Comment by wjlove** [comment]
Using balena-staging.com:  1)  Added a new device and flashed without modifying uEnv.txt; worked.  2) Added a new device and flashed, then edited uEnv.txt to include `meson-g12a-i2c-ee-m3-gpioa-14-gpioa-15`; worked.

Thank you.
